<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="GestionarCuentas" targetNamespace="http://BAPPT" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://BAPPT" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="GestionarCuentas_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="GestionarCuentasHttpBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema targetNamespace="http://BAPPT">
      <xsd:include schemaLocation="GestionarCuentas_InlineSchema1.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IIBIntegrationRequestMsg">
    <wsdl:part element="tns:IIBIntegration" name="IIBIntegrationParameters"/>
  </wsdl:message>
  <wsdl:message name="IIBIntegrationResponseMsg">
    <wsdl:part element="tns:IIBIntegrationResponse" name="IIBIntegrationResult"/>
  </wsdl:message>
  <wsdl:portType name="GestionarCuentas">
    <wsdl:operation name="IIBIntegration">
      <wsdl:input message="tns:IIBIntegrationRequestMsg" name="IIBIntegrationRequest"/>
      <wsdl:output message="tns:IIBIntegrationResponseMsg" name="IIBIntegrationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GestionarCuentasHttpBinding" type="tns:GestionarCuentas">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="IIBIntegration">
      <soap:operation soapAction=""/>
      <wsdl:input name="IIBIntegrationRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="IIBIntegrationResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GestionarCuentasHttpService">
    <wsdl:port binding="tns:GestionarCuentasHttpBinding" name="GestionarCuentasHttpPort">
      <soap:address location="http://localhost:7800/GestionarCuentas/GestionarCuentas"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>